### ISSUE TITLE
Property Controls Package Questions

### ISSUE THREAD

**Issue by kbondanza** [hamlim/projects#20]
Hey @hamlim,

Started to look at your property controls package. Is this package published to npm? Couldn't find it there? I was looking for @matthamlin/property-controls, how would you recommend that I install this package?

How does this package differ from https://www.npmjs.com/package/@matthamlin/react-property-controls?

Thanks!

**Comment by hamlim** [comment]
I'm most likely going to refactor the package before publishing it. That refactor will remove any react patterns from the package, moving the rendering from the package into any user space packages.

I'll open a PR for that soon and the will publish after.

**Comment by kbondanza** [comment]
Whats the benefit of having the rendering occur in the consumer packages? Does it allow for more control in the consuming packages?

**Comment by hamlim** [comment]
Yea there is more flexibility for how the inputs are rendered, just published the package: https://www.npmjs.com/package/@matthamlin/property-controls

**Comment by hamlim** [comment]
This package was a temporary placeholder for the concept: https://www.npmjs.com/package/@matthamlin/react-property-controls

This new package is a bit of a refactor, mostly around removing the built-in rendering logic.

**Comment by kbondanza** [comment]
Thanks! I'll check it out shortly.
